wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: xgboost
    huggingface_version: 4.32.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1693423910.073684
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 6
      - 11
      - 12
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 23
      4: 3.10.9
      5: 0.13.10
      6: 4.32.0
      8:
      - 5
